[project]
name = "data-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sigvardbratlie", email = "sigvard.bratlie@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-api-core>=2.29.0",
    "google-auth>=2.47.0",
    "google-cloud-storage>=3.7.0",
    "pandas>=2.3.3",
    "python-docx>=1.2.0",
    "streamlit[pdf]>=1.52.2",
    "streamlit",
    "langsmith>=0.2.0",
    "google-cloud-bigquery>=3.0.0",
    "db-dtypes>=1.0.0",
    "plotly>=5.0.0",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "statsmodels>=0.14.6",
]

[project.scripts]
data-viewer = "data_viewer:main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
