-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.checkpoint_blobs (
  thread_id text NOT NULL,
  checkpoint_ns text NOT NULL DEFAULT ''::text,
  channel text NOT NULL,
  version text NOT NULL,
  type text NOT NULL,
  blob bytea,
  CONSTRAINT checkpoint_blobs_pkey PRIMARY KEY (thread_id, checkpoint_ns, channel, version)
);
CREATE TABLE public.checkpoint_migrations (
  v integer NOT NULL,
  CONSTRAINT checkpoint_migrations_pkey PRIMARY KEY (v)
);
CREATE TABLE public.checkpoint_writes (
  thread_id text NOT NULL,
  checkpoint_ns text NOT NULL DEFAULT ''::text,
  checkpoint_id text NOT NULL,
  task_id text NOT NULL,
  idx integer NOT NULL,
  channel text NOT NULL,
  type text,
  blob bytea NOT NULL,
  task_path text,
  CONSTRAINT checkpoint_writes_pkey PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
);
CREATE TABLE public.checkpoints (
  thread_id text NOT NULL,
  checkpoint_ns text NOT NULL DEFAULT ''::text,
  checkpoint_id text NOT NULL,
  parent_checkpoint_id text,
  type text,
  checkpoint jsonb NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT checkpoints_pkey PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
);
CREATE TABLE public.company_details (
  company_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_name text,
  company_vat_nr text,
  created_by uuid,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_details_pkey PRIMARY KEY (company_id),
  CONSTRAINT company_details_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT company_details_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.project_attachments (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid DEFAULT gen_random_uuid(),
  file_type character varying,
  filename character varying,
  path character varying,
  size numeric,
  category character varying,
  description character varying,
  significance character varying,
  key_provisions jsonb,
  file_id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_date timestamp with time zone,
  party_roles jsonb,
  email_id uuid,
  body text,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  title text,
  CONSTRAINT project_attachments_pkey PRIMARY KEY (file_id),
  CONSTRAINT project_attachments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id),
  CONSTRAINT project_attachments_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.project_emails(email_id)
);
CREATE TABLE public.project_claims (
  claim_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  defense character varying,
  factual_basis character varying,
  legal_basis character varying,
  party_role character varying,
  relief_sought character varying,
  strength_assessment character varying,
  file_id uuid,
  project_id uuid,
  email_id uuid,
  significance text,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  category text,
  title text,
  CONSTRAINT project_claims_pkey PRIMARY KEY (claim_id),
  CONSTRAINT project_claims_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.project_emails(email_id),
  CONSTRAINT project_claims_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.project_attachments(file_id),
  CONSTRAINT project_claims_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id)
);
CREATE TABLE public.project_damages (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  category character varying,
  amount numeric,
  basis character varying,
  supporting_evidence jsonb,
  party_role character varying,
  file_id uuid,
  project_id uuid,
  damage_id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_id uuid,
  currency text,
  significance text,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  title text,
  CONSTRAINT project_damages_pkey PRIMARY KEY (damage_id),
  CONSTRAINT project_damages_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.project_emails(email_id),
  CONSTRAINT project_damages_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.project_attachments(file_id),
  CONSTRAINT project_damages_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id)
);
CREATE TABLE public.project_deadlines (
  deadline_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  description character varying,
  deadline_date timestamp with time zone,
  file_id uuid,
  party_role character varying,
  project_id uuid,
  email_id uuid,
  significance text,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  title text,
  CONSTRAINT project_deadlines_pkey PRIMARY KEY (deadline_id),
  CONSTRAINT project_deadlines_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.project_emails(email_id),
  CONSTRAINT project_deadlines_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.project_attachments(file_id),
  CONSTRAINT project_deadlines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id)
);
CREATE TABLE public.project_emails (
  email_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  from_addr text NOT NULL,
  to jsonb,
  cc jsonb,
  bcc jsonb,
  subject text,
  date timestamp with time zone,
  message_id text,
  in_reply_to character varying,
  references text,
  thread_topic text,
  thread_index text,
  thread_id text,
  body text,
  html text,
  headers jsonb,
  size numeric,
  key_points jsonb,
  description text,
  significance text,
  party_roles jsonb,
  path text,
  reference_paths jsonb,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  title text,
  CONSTRAINT project_emails_pkey PRIMARY KEY (email_id),
  CONSTRAINT project_emails_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id)
);
CREATE TABLE public.project_events (
  event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  project_id uuid DEFAULT gen_random_uuid(),
  event_name character varying,
  file_id uuid DEFAULT gen_random_uuid(),
  category character varying,
  description character varying,
  significance character varying,
  parties jsonb,
  event_start_date timestamp with time zone,
  disputed boolean,
  event_end_date timestamp with time zone,
  email_id uuid,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_events_pkey PRIMARY KEY (event_id),
  CONSTRAINT project_events_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.project_emails(email_id),
  CONSTRAINT project_events_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.project_attachments(file_id),
  CONSTRAINT project_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id)
);
CREATE TABLE public.project_parties (
  party_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  entity_type character varying,
  project_id uuid DEFAULT gen_random_uuid(),
  legal_name character varying,
  role character varying,
  key_contact jsonb,
  role_description text,
  significance text,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_parties_pkey PRIMARY KEY (party_id),
  CONSTRAINT project_parties_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id)
);
CREATE TABLE public.project_party_reps (
  party_rep_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  first_name text,
  last_name text,
  address text,
  postal_code text,
  city text,
  party_id uuid,
  rep_role text,
  rep_role_description text,
  project_id uuid,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone,
  phone text,
  email text,
  significance text,
  CONSTRAINT project_party_reps_pkey PRIMARY KEY (party_rep_id),
  CONSTRAINT project_party_representative_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id),
  CONSTRAINT project_party_representative_party_id_fkey FOREIGN KEY (party_id) REFERENCES public.project_parties(party_id)
);
CREATE TABLE public.projects (
  project_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  updated_query_id uuid DEFAULT gen_random_uuid(),
  updated_session_id uuid DEFAULT gen_random_uuid(),
  background character varying,
  title character varying,
  user_id uuid DEFAULT gen_random_uuid(),
  created_by text,
  updated_by text,
  start_date timestamp with time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (project_id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.session_attachments (
  file_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  file_type character varying,
  filename character varying,
  size numeric,
  path character varying,
  query_id uuid DEFAULT gen_random_uuid(),
  session_id uuid DEFAULT gen_random_uuid(),
  event_id uuid DEFAULT gen_random_uuid(),
  body text,
  CONSTRAINT session_attachments_pkey PRIMARY KEY (file_id),
  CONSTRAINT session_attachments_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.session_events(event_id),
  CONSTRAINT session_attachments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id)
);
CREATE TABLE public.session_events (
  event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  type character varying,
  order numeric,
  data jsonb,
  langchain_id character varying,
  query_id uuid NOT NULL DEFAULT gen_random_uuid(),
  content character varying,
  CONSTRAINT session_events_pkey PRIMARY KEY (event_id),
  CONSTRAINT session_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(session_id)
);
CREATE TABLE public.sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  title character varying,
  project_id uuid DEFAULT gen_random_uuid(),
  llm_model character varying,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(project_id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_details (
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid DEFAULT gen_random_uuid(),
  user_role character varying,
  user_first_name character varying,
  user_last_name character varying,
  CONSTRAINT user_details_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_details_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company_details(company_id),
  CONSTRAINT user_details_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);