[logging]
level = "info"

[logging.file]
enabled = true
level = "debug"
path = "log/app.log"

[logging.console]
level = "info"

[async]
max_concurrent_requests = 20
throttle_value = 0.0

[models.together]
base_url = "https://api.together.xyz/v1"
max_tokens = 4096

[agent]
max_token_tool = 10000
sum_rate = 20
embed_to_vectorstore = true
save_to_storage = true
use_factsheet = false
prompt_file_path = "system_prompt_rag.txt"

[project]
threshold = 5120000     # 500 * 1024
max_attachments = 10
max_emails = 15
embed_to_vectorstore = true
save_to_storage = true
