[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sigvardbratlie", email = "sigvard.bratlie@gmail.com" }
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "fastapi>=0.128.0",
    "google-cloud-bigquery>=3.40.0",
    "google-cloud-firestore>=2.22.0",
    "google-cloud-storage>=3.7.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-google-community[featurestore]>=3.0.3",
    "langchain-google-genai>=4.1.3",
    "langchain-openai>=1.1.7",
    "langchain-tavily>=0.2.16",
    "langgraph>=1.0.5",
    "langgraph-checkpoint-postgres>=3.0.4",
    "pandas-gbq>=0.33.0",
    "psycopg[binary,pool]>=3.3.2",
    "psycopg2-binary>=2.9.11",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.2.1",
    "supabase>=2.27.2",
    "tiktoken>=0.12.0",
    "uvicorn>=0.40.0",
    "pytest>=9.0.2",
    "pytest-asyncio>=0.25.2",
    "pydantic>=2.12.5",
    "python-pptx>=1.0.2",
    "langchain>=1.2.3",
    "langchain-core>=1.2.13",
    "langchain-anthropic>=1.3.4",
    "ocrmypdf>=16.13.0",
    "amazon-textract-response-parser>=1.0.3",
    "amazon-textract-prettyprinter>=0.1.4",
    "amazon-textract-caller>=0.2.4",
    "amazon-textract-textractor>=1.9.2",
    "pymupdf4llm>=1.27.2.1",
    "pypdf2>=3.0.1",
    "pdf2image>=1.17.0",
    "python-docx>=1.2.0",
    "markitdown[docx,pptx,xlsx]>=0.1.5",
]

[project.scripts]
agent = "agent:main"

[tool.pytest.ini_options]
log_level = "WARNING"
asyncio_mode = "auto"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
